# Generated by Django 3.2.7 on 2021-09-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockscreener', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.DeleteModel(
            name='Preferences',
        ),
    ]
