# Generated by Django 3.2.7 on 2021-09-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockscreener', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='savedsearch',
            constraint=models.UniqueConstraint(fields=('stock', 'user'), name='unique_searches'),
        ),
    ]
