# Generated by Django 3.2.7 on 2021-09-06 21:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stockscreener', '0003_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 6, 21, 10, 41, 190746, tzinfo=utc)),
        ),
    ]
