# Generated by Django 3.2.7 on 2021-09-06 21:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stockscreener', '0004_search_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 6, 21, 13, 51, 702524, tzinfo=utc)),
        ),
    ]
