# Generated by Django 3.2.7 on 2021-09-06 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockscreener', '0005_alter_search_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
