# Generated by Django 3.2.7 on 2021-09-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockscreener', '0006_alter_search_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Search',
            new_name='SavedSearch',
        ),
    ]
