# Generated by Django 3.2.7 on 2021-09-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockscreener', '0007_rename_search_savedsearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedsearch',
            name='searcher',
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='notes',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='searchers', to='stockscreener.SavedSearch'),
        ),
    ]
